leifg/formulon

README.md, package.json
- better code quoting
- badges
=> Improve docs

test/ast.spec.js
=> increase timout for long test

grammars/salesforceFormula.pegjs, test/ast.spec.js
change pegjs grammar to allow it
fixes #109
=> Allow whitespaces in front of function calls

grammars/salesforceFormula.pegjs, src/functions.js, test/ast.spec.js, test/formulon.spec.js, test/functions.spec.js
Find the longest arithmetic expression of the same precedence and then
treat is as addition or multiplication.
fixes #114
=> handle arithmetics with same precedence correctly

src/utils.js, test/utils.spec.js
otherwise weird things would happen on different computers
=> Make sure date is always in UTC

src/utils.js, test/utils.spec.js
=> Implement null data type

src/formulon.js, test/formulon.spec.js
=> Implement formatter

src/formulon.js, src/utils.js, test/formulon.spec.js, test/utils.spec.js
=> Add datetime data type

src/formulon.js, src/functions.js, src/utils.js, test/formulon.spec.js, test/functions.spec.js, test/integration.spec.js, test/utils.spec.js
=> Implement picklist data type

.circleci/config.yml, package.json, test/integration.json, test/integration.spec.js
=> Add integration test for Account Rating

src/formulon.js, src/functions.js, src/utils.js, test/formulon.spec.js, test/functions.spec.js, test/utils.spec.js
=> Implement geolocation data type

test/functions.spec.js
=> Fix flaky test

src/formulon.js, src/utils.js, test/formulon.spec.js, test/functions.spec.js, test/utils.spec.js
=> Implement multipicklist data type

src/errors.js, src/functionDispatcher.js, src/functions.js, src/utils.js, src/validations.js, test/functions.spec.js, test/utils.spec.js
=> Implement addition for date/time/datetime

src/functionDispatcher.js, src/functions.js, src/utils.js, test/functions.spec.js
=> Implement subtraction for date/time/datetime

grammars/salesforceFormula.pegjs, src/validations.js, test/ast.spec.js, test/integration.json, test/integration.spec.js, test/validations.spec.js
and fix all bugs necessary to do so
=> Add integration tests

src/formulon.js, test/formulon.spec.js
=> Make toString robust against null and undefined

src/functionDispatcher.js, src/functions.js, src/validations.js, test/functions.spec.js, test/validations.spec.js
=> Implement comparables for all supported data types

test/integration/01_account_management.json, test/integration/02_account_media_service.json, test/integration/03_case_management.json, test/integration/04_commission_calculations.json, test/integration/05_contact_management.json, test/integration/06_data_categorization.json, test/integration/07_date.json, test/integration/08_discounting.json, test/integration/09_employee_services.json, test/integration/10_expense_tracking.json, test/integration/11_financial_calculations.json, test/integration/12_image_link.json, test/integration/13_integration_link.json, test/integration/14_lead_management.json, test/integration/15_metrics.json, test/integration/16_opportunity_management.json, test/integration/17_pricing.json, test/integration/18_scoring_calculations.json, test/integration/index.spec.js
=> Integration Tests #3

README.md
Adding @jordanhenderson to contributors list. Any objections
=> docs: add @jordanhenderson to contributors list

README.md
Address questions about use cases in #561
=> Add section about use cases

src/utils.js, test/formulon.spec.js, test/utils.spec.js
=> fix: make sure empty numbers are properly coerced

grammars/salesforceFormula.peggy, src/ast.js, src/formulon.js, src/functions.js, src/utils.js, test/ast.spec.js, test/formulon.spec.js, test/functions.spec.js, test/integration/11_financial_calculations.json, test/integration/15_metrics.json, test/integration/index.spec.js, test/utils.spec.js, yarn.lock
- Only use Decimal Library when operating arithmetic operations
- Make API of formulon compatible again (returning Number instead of Decimal)
=> dont expose decimal library

.github/workflows/auto-merge.yml
As suggested in ahmadnassri/action-dependabot-auto-merge#120
=> fix auto merge job 01: Naming

grammars/salesforceFormula.peggy, test/ast.spec.js, test/shared.js
=> fix: allow brackets for identifier names

src/functions.js, test/functions.spec.js
=> Properly type check in multiply/divide/exponentiate

src/functions.js, test/functions.spec.js
=> fix: implement concatenation for string and null value

src/functionDispatcher.js, src/functions.js, test/functions.spec.js
=> feat: implement isnull and nullvalue

grammars/salesforceFormula.peggy, test/shared.js
=> Make unary operator possible in concatenated logic expressions

src/functionDispatcher.js, test/unit/functions.spec.js
=> Make time comparable
